### PR TITLE
Fix EZP-25189: Richtext tollbar container doesn't render correctly on IE11/Edge

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25189

# Description

Replaces https://github.com/ezsystems/PlatformUIBundle/pull/462
This is fixing a display issue in IE11 (and Edge) because of IE10+ specific rule setting a fixed height in the AlloyEditor CSS (we can not really change that in our skin).

While at it, I also fixed a small gap between the toolbar tail and the toolbar itself.

# Tests

manual test in IE11, Chrome and Firefox (currently installing a VM to test with Edge)

### CODE REVIEW

**Comment by dpobel** [comment]
ping @mhyndle @andrerom @yannickroger

**Comment by andrerom** [comment]
+1

**Comment by mhyndle** [comment]
+1

**Comment by dpobel** [comment]
Edge seems happy with this patch

**Pull request merged**
