### PR TITLE
Fix EZP-24452: Add cancel button in ContentType edition form

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24452

Depends on https://github.com/ezsystems/repository-forms/pull/29

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @dpobel @andrerom @bdunogier @glye @pspanja @yannickroger

**Comment by andrerom** [comment]
+1

**Comment by lolautruche** [comment]
Fixed the PR link, sorry :blush:

**Comment by glye** [comment]
+1
(Unrelated: This removes only content type drafts, so no issue with also removing a million content objects, but we'll burn that bridge when we get to it...)

**Pull request merged**
