### PR TITLE
Fix EZP-25072: Deletion of "Role Assignment" redirects to wrong location

### PR DESCRIPTION
**Pull request by glye**
> Fixes https://jira.ez.no/browse/EZP-25072
> Status: Ready for review
> Depends on https://github.com/ezsystems/PlatformUIBundle/pull/438

This uses the tab loading feature I added in https://github.com/ezsystems/PlatformUIBundle/pull/438, so it can only be merged after that.
Behat test fail is irrelevant.

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Comment by bdunogier** [comment]
@dpobel ? Is this mergeable or irrelevant for now ?

**Comment by glye** [comment]
@bdunogier Not mergeable until parent PR is merged, see description.

**Comment by andrerom** [comment]
Closing *temporary* and moving this to [a later epic](https://jira.ez.no/browse/EZP-25442) as this needs to be handled after generic refresh system is in place.

**Pull request closed without merging**
