### PR TITLE
Fix EZP-26996: typo in translation for locationview.details.remoteid

### PR DESCRIPTION
**Pull request by wizhippo**

### CODE REVIEW

**Comment by wizhippo** [comment]
@dpobel I believe I have done as you asked.

**Comment by bdunogier** [comment]
> @bdunogier / @yannickroger Does this affect the i18n packages?

Yes it does, starting from 1.8, using the new `bin/extract-translations.sh`.
The strings also need to be generated for 1.7, but the script is probably different.

**Comment by bdunogier** [comment]
After talking to Damien, no need to run any script, since the english string only exists in translation files.

What will have to be done is execute `bin/synchronize-translations.sh` from ezplatform after the merge, and commit to ezsystems/ezplatform-i18n after the sync.

**Comment by dpobel** [comment]
perfect @wizhippon, I'm merging and taking care of forward porting :) thanks again

**Pull request merged**
