### PR TITLE
Fixed EZP-23914: Image and Media edit views display are broken in IE10

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-23914

# Description

Fix the layout in IE10 when editing an Image or Media field. (The patch was made a while ago but for whatever reason, I forgot to create the PR...)

# Tests

manual tests

### CODE REVIEW

**Comment by dpobel** [comment]
ping @yannickroger @StephaneDiot @mhyndle

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by StephaneDiot** [comment]
+1

**Pull request merged**
