### PR TITLE
[WIP] Fix EZP-24905 Role assignment limitations

### PR DESCRIPTION
**Pull request by glye**
Work in progress, based on https://github.com/ezsystems/PlatformUIBundle/pull/344

Not working yet. The gist of `RoleServerSideView` is:
- The "Assign to..." button calls `_pickAssignee()` which is used when assigning a role without limitation; this is working.
- The "Assign to... with subtree limitation" button calls `_pickAssigneeLimitSubtree()`, used for assigning with limit on subtree. This fires a UDW for selecting subtree, whose `contentDiscoveredHandler` calls `__pickAssigneeLimitSubtreeAssign()`. That function should fire a UDW for selecting users/groups to assign to, but this fails silently.
- The "Assign to... with section limitation" button starts a new view with a section select dropdown. The Assign button in this view should use JS to read the selected section ID (currently hardcoded to 3) and pass it in the button attribute `data-role-assignment-section-id`. The button calls `_pickAssigneeLimitSection()` which fires a UDW for selecting users/groups. The UDW opens, but when selecting something it fails with "TypeError: s is undefined oop-min.js:8:1932"

- [x] PHP and templates
- [ ] Rebase once https://jira.ez.no/browse/EZP-24700 is stabilised/merged
- [ ] Fix loading of the second UDW when assigning by subtree limitation
- [ ] Ensure that the "assign by section limitation"-button reads section ID from the dropdown
- [ ] Fix oop-min.js error for section limitation UDW
- [ ] Remove console.log debugging lines

https://jira.ez.no/browse/EZP-24905

### CODE REVIEW

**Comment by glye** [comment]
Ping @mhyndle @dpobel @yannickroger - please have a look. See description - why won't the second UDW fire?

**Comment by glye** [comment]
Rebased on ezp-24700_role_assignment_crud

**Comment by glye** [comment]
Added template and controller for limitation by section, work in progress.

**Comment by glye** [comment]
Completed section code, apart from some javascript bits.

**Comment by mhyndle** [comment]
I have removed JS part from this PR as it will be easier to menage with that in separate issues and PRs.
- Role assignment with subtree limitation: https://jira.ez.no/browse/EZP-25008
- Role assignment with section limitation: https://jira.ez.no/browse/EZP-25009
Additionally I have rebased this PR on the ezp-24700_role_assignment_crud base.

**Comment by glye** [comment]
Closing, see https://github.com/ezsystems/PlatformUIBundle/pull/397

**Pull request closed without merging**
