### PR TITLE
BDD: change behat.yml into behat_suites.yml

### PR DESCRIPTION
**Pull request by miguelcleverti**
As discussed with @bdunogier in ezsystems/BehatBundle#42 sub-behat.yml to be included in ezplatform main behat.yml are now called behat_suites.yml

### CODE REVIEW

**Comment by bdunogier** [comment]
Hmmm, is it expected that we don't run PlatformUIBundle features in PlatformUIBundle pull requests ?

**Comment by miguelcleverti** [comment]
@bdunogier we are running the PlatformUI features, they did not run in this PR because the changes in https://github.com/ezsystems/ezplatform/pull/82 are not yet merged

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
Okay, good. Let's go for it then.

**Pull request merged**
