### PR TITLE
Fix EZP-26371: "Reset password" link does nothing.

### PR DESCRIPTION
**Pull request by joaoinacio**
JIRA: https://jira.ez.no/browse/EZP-26371

Removes currently unused link, which should be reintroduced once the feature is done/available.

### CODE REVIEW

**Comment by joaoinacio** [comment]
@andrerom : I'm guessing this should be on 1.4 as well?

**Comment by andrerom** [comment]
No 1.5 and up is fine, last 1.4 patch had been made.

**Comment by dpobel** [comment]
+1

**Comment by pcardiga** [comment]
PR verified by QA - +1

**Pull request merged**
