### PR TITLE
Fix EZP-25126: Visually unfinished language list (and Section list)

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25126

# Description

Before:
before

After:
after

# Tests

manual tests

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by dpobel** [comment]
ping @yannickroger @mhyndle

**Comment by yannickroger** [comment]
+1

**Comment by mhyndle** [comment]
+1

**Pull request merged**
