### PR TITLE
Mink stale reference fix

### PR DESCRIPTION
**Pull request by miguelcleverti**
This PR fixes the problem when the mink node element changes in the browser, and the reference in memory becomes stale - causing an exception.

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@andrerom @joaoinacio

**Comment by andrerom** [comment]
+1

**Comment by andrerom** [comment]
@miguelcleverti fixing the cs? :)

**Comment by miguelcleverti** [comment]
All fixed and ready :smiley_cat:

**Pull request merged**
