### PR TITLE
EZP-25136: As an editor, I want to be able to align embed in the RichText editor

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25136

# Description

This PR adds the button to align embed and images in the editor. To be able to store aligned image, the patch https://github.com/ezsystems/ezpublish-kernel/pull/1572 is necessary.

When aligned, the embed tag receives ~~either `ez-object-align-left`, `ez-object-align-center` or `ez-object-align-right` as a class.~~ a `data-ezalign` attribute which is then passed a parameter in the embed template (example: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content.html.twig#L8)

Screencast:
[Align image and embed](http://www.youtube.com/watch?v=Sjchdh4_ZYs)

## Tasks

* [x] Add an alignment API on the embed widget
* [x] Add the buttons to align the embeds and images
* [x] Update the icons (once https://github.com/ezsystems/PlatformUIBundle/pull/503 is merged)
* [x] Investigate [EZP-25448](https://jira.ez.no/browse/EZP-25448) https://github.com/ezsystems/ezpublish-kernel/pull/1572
* [x] Find a solution for the toolbar position on paragraph when a previous embed is on the left
* [x] Use the `data-ezalign` attribute instead of a class

# Tests

unit tests + manual test

### CODE REVIEW

**Comment by dpobel** [comment]
ping @yannickroger @StephaneDiot @andrerom

**Comment by StephaneDiot** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by dpobel** [comment]
actually, I've just realized that I set a `class` to store the alignment but it seems the template for RichText in https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content.html.twig#L8 is also able to handle an `align` parameter. So I guess, I should use it instead.

**Comment by dpobel** [comment]
ping @StephaneDiot @yannickroger please review the last commit

**Comment by yannickroger** [comment]
still +1

**Comment by StephaneDiot** [comment]
+1

**Pull request merged**
