### PR TITLE
EZP-28146: Unable to replace an image - UDW does not allow me to confirm an image selection

### PR DESCRIPTION
**Pull request by dew326**
**Jira ticket:** https://jira.ez.no/browse/EZP-28146

### CODE REVIEW

**Comment by andrerom** [comment]
Should this go in older branches also perhaps?

**Comment by dew326** [comment]
1.7 is not affected and the 1.12 branch doesn't exist so I assume we keep master as 1.12 for now?

**Comment by andrerom** [comment]
@dew326  Yes

**Comment by lserwatka** [comment]
I created 1.12 branch, and configured master for 1.13.x-dev

**Pull request merged**
