### PR TITLE
EZEE-1908: More button not visible on siteaccess selection bar in Page

### PR DESCRIPTION
**Pull request by dew326**
**Jira ticket:** https://jira.ez.no/browse/EZEE-1908

### CODE REVIEW

**Comment by lserwatka** [comment]
@micszo we need a round of QA here.

**Comment by m-tyrala** [comment]
I'm doing it already.

**Comment by micszo** [comment]
@m-tyrala great, thanks. 💪

**Comment by dew326** [comment]
Closed in favor of https://github.com/ezsystems/StudioUIBundle/pull/889

**Pull request closed without merging**
