### PR TITLE
EZP-24711: Role policy editing step 1 & 2

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24711

### CODE REVIEW

**Comment by andrerom** [comment]
This was the one needing some cleanup now right?

**Comment by lolautruche** [comment]
Yes, I'm on it.

**Comment by lolautruche** [comment]
Now fully working and ready for final review!

Ping @andrerom @bdunogier @yannickroger @glye

**Comment by bdunogier** [comment]
+1

**Comment by glye** [comment]
+1

**Pull request merged**
