### PR TITLE
EZP-24873: Use the location search to build the content tree

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-24873

# Description

This patch changes the loading mechanism behind the content tree. With this patch, the tree is loaded with the Location search and this greatly improves the loading time since this decreases the number of HTTP Requests.

Before this patch there were 1 request per level + 3 requests per displayed content.
With this patch, there are 1 request per level + 1 by displayed content (for the content type).

This also changes the selection returned by the UDW since we don't have the content any more.

## Tasks

* [x] Change the content tree plugins (base + discovery + udw) to use the Location search
* [x] Fix the UDW since we have the content info instead of the content
* [x] Fix usage of the UDW selection
  * [x] Copy content
  * [x] Move location
  * [x] Add location
  * [x] Relation edit
  * [x] RelationList edit
  * [x] Embed in the RichText editor
  * [x] Content type edit (Relation and RelationList)
  * [x] Section assignment
  * [x] Role assignment
* [ ] ~~TBD: Fix the order of contents because of the lack of server side sorting ([EZP-24315](https://jira.ez.no/browse/EZP-24315))~~ https://jira.ez.no/browse/EZP-24998
* [ ] ~~Nice to have: Smarter content types loading~~ https://jira.ez.no/browse/EZP-25012

# Tests

unit tests + manual test

### CODE REVIEW

**Comment by dpobel** [comment]
review ping @yannickroger @mhyndle @andrerom @StephaneDiot 

BC break warning: @sunpietro @glye as of the merge of this, the UDW will not provide the content but the contentInfo.

**Comment by dpobel** [comment]
self note: need to take the UDW usage introduced in https://github.com/ezsystems/PlatformUIBundle/pull/344

**Comment by mhyndle** [comment]
+1

**Comment by dpobel** [comment]
ping @yannickroger @StephaneDiot @andrerom

**Comment by andrerom** [comment]
+1

**Comment by dpobel** [comment]
ping @sunpietro I'm merging this PR, don't forget to adapt the Studio's `contentDiscoveredHandler` to use the content info instead of the content (see the examples in this PR).

**Comment by sunpietro** [comment]
@dpobel thanks for notification, I'll take a look at this.

**Pull request merged**
