### PR TITLE
Fix EZP-25941: Avoid empty search when there's no embed/image

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25941

# Description

Avoid doing a search request to resolve the *embed* and *embed image* when there's none.

Replaces a part of #623 

# Tests

manual tests + unit tests

### CODE REVIEW

**Comment by dpobel** [comment]
ping @mathieupoulenard @StephaneDiot

**Comment by StephaneDiot** [comment]
+1

**Comment by mathieupoulenard** [comment]
+1

**Comment by aymericDD** [comment]
+1

**Pull request merged**
