### PR TITLE
Change ezpublish to app in README.md file

### PR DESCRIPTION
**Pull request by crevillo**
Following with the ezpublish to app renames. Let me know if you want me to add a jira issue for this or is this could work without it
ping @dpobel @andrerom @bdunogier @yannickroger

### CODE REVIEW

**Comment by bdunogier** [comment]
+1 here.

@dpobel ?

**Comment by andrerom** [comment]
+1

**Comment by dpobel** [comment]
+1

**Comment by bdunogier** [comment]
As pointed out by @dpobel, the instructions here don't make much sense, when you think about it. Given that PlatformUI outside of eZ Platform doesn't make much sense, there's not much point in maintaining these instructions.

I'll merge it for now, but we might wanna refactor those README files so that they all reference ezplatform's.

**Comment by bdunogier** [comment]
Merged to 8f03ad0 (changed the commit message).

**Comment by crevillo** [comment]
thanks @bdunogier. while on this. should we remove "ezpublish" references in eZ Platform provided routing.yml? Lide this one https://github.com/ezsystems/ezplatform/blob/master/app/config/routing.yml#L24.
There's no problem with the way they are defined now, but as we're trying to get ride of ezpublish...

**Comment by bdunogier** [comment]
It's a good idea, @crevillo. But we have a few ones that will be harder to cover, like the name of the root key for the settings, the name of the CoreBundle... :-)

**Pull request closed without merging**
