### PR TITLE
Fix EZP-24786: ContentType and Role creation must use POST

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24786

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @dpobel @yannickroger @glye

**Comment by andrerom** [comment]
+1

Any conflicts @glye should be aware of?

**Comment by lolautruche** [comment]
@andrerom @glye AFAICT should not cause any problem.

**Comment by glye** [comment]
+1, conflicts should be minimal, if any.

**Pull request merged**
