### PR TITLE
Changed the way the REST API Client is imported in YUI sandbox

### PR DESCRIPTION
**Pull request by dpobel**
# Description

This patch improves the way the REST API Client is *imported* in the YUI sandbox. Now, this is unit tested and in addition, we and external contributor can use the same strategy when an external library is needed.

# Tests

manual + unit test

### CODE REVIEW

**Comment by dpobel** [comment]
ping @yannickroger @mhyndle @StephaneDiot

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by StephaneDiot** [comment]
+1

**Pull request merged**
