### PR TITLE
Fix EZP-25921: refresh the Content Tree after swapping Location

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25921

# Description

This was forgotten in #592 

# Tests

manual + unit tests

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by crevillo** [comment]
Wops, my bad... +1.

**Comment by dpobel** [comment]
no worries @crevillo :)

**Comment by andrerom** [comment]
Seems we have similar issue for sub items? https://jira.ez.no/browse/EZP-25950

**Comment by dpobel** [comment]
@andrerom did not check the details yet but I think it's a server side issue in that case

**Comment by andrerom** [comment]
Ok, if it is mark as duplicate of EZP-25003.

**Pull request merged**
