### PR TITLE
EZP-24727: Admin form formating/styling for sections

### PR DESCRIPTION
**Pull request by andrerom**
Merge in master and apply formating like other forms.

For merge into #288, only last commit is relevant here as the others comes from the merge from master and will be gone if #288 and then this is rebased before review and merge.

How it looks:
screen shot 2015-08-29 at 22 18 31

### CODE REVIEW

**Comment by andrerom** [comment]
Hmm.. tought github used to be more smart when it comes to PR against PR.

**Comment by andrerom** [comment]
Guess the other PR needs to be rebased first before this one is on top of it, or just cherry-pick the last commit into your PR if your ok with the change and we can close this one and rather review it on the other.

**Comment by andrerom** [comment]
@lolautruche Rebased, ready for review and potential merge into your PR now.

**Comment by lolautruche** [comment]
+1 Thanks

**Pull request merged**
