### PR TITLE
Fix EZP-25530: Allow saving DateAndTime on Firefox

### PR DESCRIPTION
**Pull request by yannickroger**
Link: https://jira.ez.no/browse/EZP-25530

## Description
Firefox doesn't support (yet ?)  `get('valueAsNumber')`. This patch refactors a bit to use the input's value and parses it until we improve the general behavior of DateAnd time field on Firefox in [EZP-23925](https://jira.ez.no/browse/EZP-23925)

## Tests
Manual test on FF and chrome.

### CODE REVIEW

**Comment by andrerom** [comment]
*Side: Would this have been detected if we had unt tests running on more js/browser engines?*

**Comment by yannickroger** [comment]
@andrerom most likely yes.

**Comment by glye** [comment]
+0.5 (JS handicap). Weird that I could not reproduce this, am using FF.

**Comment by dpobel** [comment]
+1

**Comment by StephaneDiot** [comment]
+1

**Pull request merged**
