### PR TITLE
EZP-21821- BDD for edit view for ezuser fields

### PR DESCRIPTION
**Pull request by miguelcleverti**
BDD test for the fields view of ezusers.
PS: also minor doc comment fix of the name of the files

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@andrerom @joaoinacio @pcardiga @bdunogier review pls
ps: (#360) I don't think ezrobot was drunk ,the line [56 in ContentUserGateway.php] (https://github.com/ezsystems/PlatformUIBundle/blob/master/Rest/ContentUserGateway.php#L56) still looks wrong. Shouldn't it be `if (strtolower($mediaType) !== 'application/vnd.ez.api.contentcreate') {`. I would fix it in this PR but it would be really out of scope IMO

**Comment by miguelcleverti** [comment]
@andrerom @joaoinacio @pcardiga @bdunogier

**Comment by andrerom** [comment]
+1 Passing? :)

**Comment by miguelcleverti** [comment]
@andrerom Yes, passing :+1:

**Pull request merged**
