### PR TITLE
Improved the style of the dashboard blocks

### PR DESCRIPTION
**Pull request by dpobel**
# Description

This patch simplifies and improves the CSS for the dashboard. So now, the style is closer to the original specifications, here is a screencast with 3 blocks (even if we have 2 at the moment) to show the responsive the behaviour:

[](http://www.youtube.com/watch?v=2FRMIuNBYxc "Click to play on Youtube.com")

# Tests

manual tests

### CODE REVIEW

**Comment by dpobel** [comment]
ping @yannickroger @StephaneDiot

**Comment by andrerom** [comment]
+1

**Comment by StephaneDiot** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Pull request merged**
