### PR TITLE
EZEE-1876: "Confirm" event data fired by Y.eZ.DraftConflictView._confirmDraftEdition should contain selected version id and status

### PR DESCRIPTION
**Pull request by adamwojs**
> JIRA: https://jira.ez.no/browse/EZEE-1876

## Description 

This PR adds id and status of selected version in the `confirm` event data fired by `Y.eZ.DraftConflictView._confirmDraftEdition`

### CODE REVIEW

**Comment by sunpietro** [comment]
I'm missing the description why it's needed. What problem it solves?

**Comment by adamwojs** [comment]
@sunpietro I need it for https://github.com/ezsystems/StudioUIBundle/pull/890 to be able to redirect editor to selected version of the landing page. See https://github.com/ezsystems/StudioUIBundle/pull/890/commits/6fb1feab769bbb3922a3f161d7c0c65862ee072a#diff-22fe29932eeed29a81c0f1f056150054R164

**Comment by sunpietro** [comment]
My proposal is that you should refactor a bit the code to be able to use a custom plugin (from the StudioUIBundle) that changes a way of redirecting a user to a proper version. If we are going to follow the rules that were previously introduced, that is no unneccesary code related to Studio inside the PlatformUI codebase, then it's the only way.

cc @andrerom @lserwatka

**Comment by Nattfarinn** [comment]
A can agree that we should still avoid making unnecessary dependencies between PlatformUI and StudioUI, but it's not a dependency here. Additional code is used by Studio, thats true, but it's not related to Studio code base in any way.

I guess explanation here would be enough, because it is just exposing more information we already have in Platform and use in the event from the very same `a href` element.

It's more like an improvement on existing extensibility point.

**Comment by andrerom** [comment]
Assuming @sunpietro is now ok with this, then this has enough approvals to be sent to QA here @adamwojs

**Comment by adamwojs** [comment]
@micszo This issue is caused by missing changes from https://github.com/ezsystems/ezpublish-kernel/pull/2268 in your installation (Platform UI counterpart is already included in this branch). 

Please apply patch from above PR or change the "ezsystems/ezpublish-kernel" dependency to "~6.13@dev"  in your `composer.json` and everything should be fine 😉

**Comment by micszo** [comment]
@adamwojs Switching to branch 6.13 in kernel helps, applying patch doesn't (hunk succeeds with offset).

**Pull request merged**
