### PR TITLE
[EZP-24846] BDD sentences for users that should not be able to login

### PR DESCRIPTION
**Pull request by miguelcleverti**
BDD tests for the issue:
https://jira.ez.no/browse/EZP-24846

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@andrerom @pcardiga

**Comment by andrerom** [comment]
+1, but this will need fixes before it can merged.

**Comment by bdunogier** [comment]
Hmm, I might not have phrased it this way. By reading the 3 scenarios, you don't really know who's supposed to be able to login...

And fact is that *we* don't really know that :(

**Comment by andrerom** [comment]
Looking back at this, why is this passing?

**Comment by miguelcleverti** [comment]
@andrerom they are not, this was before the BDD tests were running in CI

**Comment by bdunogier** [comment]
Needs more work. The roles that are used don't exist anymore (at least for some), due to the cleandata/demo changes.

Furthermore, I suggest that we cover the actually expected behaviour:

```
Given I am on to the PlatformUI login page
When I log in as a user who doesn't have permissions to use PlatformUI
Then I get an error message saying "..."
```

**Comment by bdunogier** [comment]
Closing it since most of it must be changed.

**Pull request closed without merging**
