### PR TITLE
Fix-EZP-28398: Using Assetic versioning breaks Platform Admin UI

### PR DESCRIPTION
**Pull request by kmadejski**
JIRA issue: https://jira.ez.no/browse/EZP-28398

Fix for 1.12.x.

### CODE REVIEW

**Comment by micszo** [comment]
@kmadejski what about 1.7? (1.7.6 is marked in ticket) 🙂

**Comment by kmadejski** [comment]
@micszo There is PR for 1.7: https://github.com/ezsystems/PlatformUIBundle/pull/927

**Comment by micszo** [comment]
@kmadejski have you found out what's wrong with travis? 🙂

**Comment by kmadejski** [comment]
@micszo yes, none of these problems are related to my PRs. 

PhantomJS tests failed as well in master: https://travis-ci.org/ezsystems/PlatformUIBundle/builds/312889318

Behat tests failed because of change in fos-http-cache which @andrerom did today: 
```  
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException] The service "fos_http_cache.user_context.hash_generator" has a dependency on a non-existent service "ezpublish.user.identity_definer.role_id".  
```

**Comment by andrerom** [comment]
behat should be back to green now.

@micszo On the JS failures those where broken a month or two ago by @dew326 and @piotr-szczygiel, they have promised to fix it before release next week ;)

**Comment by micszo** [comment]
@andrerom did you mean @sunpietro ? ;)

**Comment by dew326** [comment]
it wasn't me ;)
but I think, I wrote solution here: https://github.com/ezsystems/PlatformUIBundle/pull/916#issuecomment-342072525

**Comment by sunpietro** [comment]
I have it on my todo list.

**Comment by kmadejski** [comment]
@andrerom thanks, Behat is green now! ping @micszo

**Pull request merged**
