### PR TITLE
[Behat] Add country fieldtype BDD tests

### PR DESCRIPTION
**Pull request by miguelcleverti**
Behat tests for platformUI country fieldtype

depends on: https://github.com/ezsystems/BehatBundle/pull/51

### CODE REVIEW

**Comment by miguelcleverti** [comment]
Closing as obsolete

**Comment by andrerom** [comment]
@miguelcleverti When you say obsolete, are you implying it has been solved by other PR's?

**Comment by miguelcleverti** [comment]
@andrerom I closed this because a long time ago we decided to not make test for all fieldtypes. Also this PR is really old, things have changed since then and if needed I will reopen no need for it to stay opened indefinitely.

**Comment by andrerom** [comment]
ok

**Pull request closed without merging**
