### PR TITLE
Added branch alias

### PR DESCRIPTION
**Pull request by lolautruche**

### CODE REVIEW

**Comment by lolautruche** [comment]
Ping @andrerom @bdunogier @pspanja @glye @dpobel

**Comment by bdunogier** [comment]
+1. Even though the phpunit dep change doesn't really belong into this commit ;-)

**Comment by lolautruche** [comment]
Forgot to do a `git add -p`... Will fix

**Comment by lolautruche** [comment]
Fixed

**Comment by andrerom** [comment]
+1

**Pull request merged**
