### PR TITLE
EZP-28006: More user friendly date format in draft conflict pop-up

### PR DESCRIPTION
**Pull request by dew326**
**Jira ticket:** https://jira.ez.no/browse/EZP-28006

### CODE REVIEW

**Comment by micszo** [comment]
@dew326 what about 1.7? :)

**Comment by dew326** [comment]
@micszo user-friendly dates were introduced in 1.8, so it's not possible to fix it in 1.7.

**Comment by lserwatka** [comment]
@dew326 please marge up to master

**Comment by dew326** [comment]
Done

**Pull request merged**
