### PR TITLE
EZP-24062: Added the full selection list display to the confirmed list

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-24062

# Description

This patch adds the ability for the editor to display the complete selection in the universal discovery widget when it is configured to allow several contents to be selected. In later stories, we'll implement two buttons on each content in the selection; [one to get a complete overview of the content](https://jira.ez.no/browse/EZP-24064) and [another one to remove the content from the selection](https://jira.ez.no/browse/EZP-24063).

Screencast: http://youtu.be/7SX3zeLsuDM

## Tasks

* [x] Implement the full selection display
* [x] Hide the full selection when clicking outside of the list
* [x] Differentiate the close icon from the remove icon
* [x] Complete CSS

# Tests

manual tests + unit tests

### CODE REVIEW

**Comment by dpobel** [comment]
ping @yannickroger @StephaneDiot

**Comment by StephaneDiot** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by dpobel** [comment]
ping @sunpietro 
This patch renames the `font-icon` class to `ez-font-icon`, so if you use it in Studio, you'll have to use the new name. To do that, you can just run the following command from the root of the bundle:
```bash
$ find Resources/ -type f -exec sed -i s/font-icon/ez-font-icon/g {} \;
```

**Pull request merged**
