### PR TITLE
EZP-25108: As an editor, I want to able to embed images in the RichText editor

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25108

# Description

This patch adds the ability to add images in the RichText editor. It's basically a specific UI to embed contents with a filled `ezimage` field. It only provides the very basic feature.

Screencast: http://youtu.be/-JIZIAIQ-W8

## Out of the scope of this PR / Bugs / Follow up

* **Bug** [EZP-25000: Empty embed when editing a RichText](https://jira.ez.no/browse/EZP-25000)
* [EZP-25138: Smooth transition after choosing an image](https://jira.ez.no/browse/EZP-25138)
* [EZP-25135: Ability to choose the image alias](https://jira.ez.no/browse/EZP-25135)
* [EZP-25136: Align handling](https://jira.ez.no/browse/EZP-25136)
* [EZP-25137: Ability to create an Image to embed it](https://jira.ez.no/browse/EZP-25137)

## Tasks

* [x] Add an option to the UDW so it can provide the Content
* [x] Improve the `ezembed` widget API to consistently handle those widgets with the buttons
* [x] Add a way to configure the event that are forwarded from the editor the YUI stack
* [x] Add a custom callback to the `loadImageVariation` event
* [x] Add a method in ContentType model to get the field identifier of a given type
* [x] Add the Image button
* [x] Add the config the Image styling toolbar
* [x] Add the change Image button for embed representing an image
* [x] CSS
* [ ] ~~Smooth transition/interaction~~ moved to [EZP-25138](https://jira.ez.no/browse/EZP-25138) as the PR is already too big.
* [x] Create the follow up stories/improvements

# Tests

manual tests + unit test

### CODE REVIEW

**Comment by dpobel** [comment]
ping @andrerom @yannickroger @mhyndle @StephaneDiot

**Comment by andrerom** [comment]
+0.99

**Comment by yannickroger** [comment]
+1,0099999999999999999999999999999999999999999999999999999 :)

**Comment by dpobel** [comment]
for the record:
```
$ node -e 'console.log(+0.99 + +1.0099999999999999999999999999999999999999999999999999999)'
2
```

**Comment by mhyndle** [comment]
+1

**Comment by mhyndle** [comment]
Sorry, missclicked (need coffee).
+1

**Pull request merged**
