### PR TITLE
EZP-24699: Enrich policy limitations view with human readable names

### PR DESCRIPTION
**Pull request by adamwojs**
> JIRA: https://jira.ez.no/browse/EZP-24699
> **Requires merge first**: https://github.com/ezsystems/repository-forms/pull/159

# Description 

This PR makes the values of policy limitations readable to humans. See https://github.com/ezsystems/repository-forms/pull/159 for more details

zrzut ekranu 2017-10-11 o 10 25 23

# TODO

- [X] Implementation
- [x] Tests

### CODE REVIEW

**Comment by andrerom** [comment]
Any reason why you use `;` over `,` ? :)

**Comment by andrerom** [comment]
@adamwojs what is remaining here for the `wip`?

**Comment by andrerom** [comment]
Ah, the behat failures seems relevant, getting some help from QA on that?

**Comment by adamwojs** [comment]
@andrerom I think that could speed up things, also I haven't fixed tests yet, because we still waiting for PM feedback. 😉

**Comment by SylvainGuittard** [comment]
To make the limitations easy to read, I prefer to have `<br>` instead of `;`
Here is the screenshot of the interface for eZ Platform v2.
image
If we can have the same rendering for the limitations, it will improve the user experience (v1 -> v2).

**Comment by adamwojs** [comment]
PR updated according to @SylvainGuittard suggestions.

**Comment by SylvainGuittard** [comment]
Thank you so much @adamwojs :)

**Comment by adamwojs** [comment]
@SylvainGuittard I don't see any problem, but we should make all limitation identifiers translatable.

**Comment by andrerom** [comment]
@adamwojs For the translation change _(here or as followup, check with LS)_ could you also add something like a `title` attribute on the bold part with a string like `Limitation Identifier: %identifier%` so advanced users does not loose information by humanizing this?

**Comment by SylvainGuittard** [comment]
> Did you intend for the strings to be translated btw?
We'll have to. It makes sense to have the admin interface translated. Tables and content in the tables as well.

**Comment by adamwojs** [comment]
PR updated according to @SylvainGuittard and @andrerom suggestions. I've also applied suggestions about HTML structure from https://github.com/ezsystems/ezplatform-admin-ui/pull/5

**Comment by lserwatka** [comment]
@adamwojs what tests are missing here to remove WIP from this PR?

**Comment by andrerom** [comment]
@SylvainGuittard While I can agree on the domain names, I would disagree on things like module and function names I think, they are property values that are not translatable in the system. Would be like attempting to translate class names :P But more importantly doc is only in english, looking up what these things are for would be broken if we translate them.

**Comment by adamwojs** [comment]
@lserwatka Previously the build was failing on Behat, but everything is OK after merge ezsystems/repository-forms#159 and rebase PR with current master.

**Comment by lserwatka** [comment]
Thank you @adamwojs for your contribution. @SylvainGuittard we should have a follow up story on translations. I merging this one to move things forward.

**Comment by SylvainGuittard** [comment]
@andrerom 
> I would disagree on things like module and function names I think

My bad. My comment was not very precise. I never thought about translating `module` and `function`.

Everything in the limitation column should be translated.
- `Content Type` should be `Type de Contenu` in french (according to the glossary: https://crowdin.com/translate/ezplatform/1140/en-fr) and same for all limitations
- Content Type names should be displayed in French is the content type has a french translation. Which brings another topic: the translation of content types...
- In am not sure yet about Path (`Subtree`)...

@lserwatka: 
> we should have a follow up story on translations. I merging this one to move things forward.

Sure. I will do it.

**Comment by SylvainGuittard** [comment]
@lserwatka @adamwojs follow up story: https://jira.ez.no/browse/EZP-28072

**Pull request merged**
