### PR TITLE
EZP-25002: Added buttons to add/remove options in Selection settings

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25002
Requires https://github.com/ezsystems/repository-forms/pull/99

# Description

This PR (with the one on repository-forms) adds a UI to add or remove options in Selection field definitions. This is done in a way that also allows to do it only with the keyboard.
(Correct terms in the button will be added later in https://github.com/ezsystems/repository-forms/pull/99 once the translation system is stabilized)

Screencast:

[](http://www.youtube.com/watch?v=5FOZT0hZG5w "Click to play on Youtube.com")

# Tests

manual tests + unit tests

### CODE REVIEW

**Comment by dpobel** [comment]
ping @yannickroger @StephaneDiot @bdunogier @nicolas-bastien

**Comment by dpobel** [comment]
@yannickroger @StephaneDiot QA found an issue when you remove an option in the middle of the list, apply, add an option and then apply again. To avoid that, I added 2ffa7ad (and ) in the repository-forms pull request so that options are reindexed after each removal/addition so that we don't loose any option.
Please review those last changes.

**Comment by bdunogier** [comment]
You should rebase on top of master to avoid the PHP 5.5 travis failure.

**Comment by dpobel** [comment]
@bdunogier it's for 1.6 :)

**Comment by yannickroger** [comment]
still +1

**Pull request merged**
