### PR TITLE
EZP-24723: Added the ezparagraph button to add paragraphs

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-24723

# Description

This patch adds a button to add paragraphs element to editor, basically the same as for heading.

Screencast: https://www.youtube.com/watch?v=tcNziaImsxU

# Tests

manual + unit test

### CODE REVIEW

**Comment by dpobel** [comment]
ping @yannickroger @mhyndle @StephaneDiot @andrerom

**Comment by mhyndle** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
+1

**Pull request merged**
