### PR TITLE
EZP-24801 Labels change on content edit header infos

### PR DESCRIPTION
**Pull request by StephaneDiot**
jira link: https://jira.ez.no/browse/EZP-24801

## Description 

This PR only consist in renaming labels on content edit header's info.

## Tests

- [x] manual tests

### CODE REVIEW

**Comment by StephaneDiot** [comment]
ping @dpobel @mhyndle @yannickroger

**Comment by dpobel** [comment]
+1

**Comment by StephaneDiot** [comment]
what about travis fail ?

**Comment by dpobel** [comment]
@ezrobot is drunk these days... by the way, it would be nice if someone can check why @ezrobot keeps on shouting on a code which is not there anymore, @lolautruche ou @andrerom maybe ?

**Comment by lolautruche** [comment]
It's @bdunogier 's fault. I just fixed the error, so you need to rebase on master.

**Comment by mhyndle** [comment]
+1

**Pull request merged**
