### PR TITLE
EZP-26128: As a Developer I want deprecation issues resolved, so that application logs are clean

### PR DESCRIPTION
**Pull request by alongosz**
Status: **WIP**
JIRA Story: [EZP-26128](https://jira.ez.no/browse/EZP-26128)

**TODO**:
- [x] Quote service references in Yaml files (dc35500).
- [x] Quote parameter references in Yaml files (d1b33ec).
- [x] Make sure tests are run with full error reporting (72a90fd).
- [x] Replace string references of form field types with fully-qualified type class names (94c6ba5).
- [x] Merge [repository-forms PR #93](https://github.com/ezsystems/repository-forms/pull/93) to be able to replace some form types instantiation with their fully qualified type class names, like [in this case](https://github.com/ezsystems/PlatformUIBundle/blob/1.4/Controller/SectionController.php#L84).

### CODE REVIEW

**Comment by andrerom** [comment]
I'll have a look at trying to get bdd tests to run soonish :)

**Comment by alongosz** [comment]
It looks like this is all for the `PlatformUIBundle`.
Ping @andrerom

**Comment by andrerom** [comment]
+1

ping @yannickroger

**Comment by andrerom** [comment]
ping @glye

**Comment by glye** [comment]
+1

**Pull request merged**
