### PR TITLE
Fixed YUI3 dependency in bower.json

### PR DESCRIPTION
**Pull request by adamwojs**
> JIRA: -

## Description 

YUI3 installation attempt on travis/local environment ends up with 

```
bower ECONNREFUSED  connect ECONNREFUSED 74.6.106.13:80
Stack trace:
Error: connect ECONNREFUSED 74.6.106.13:80
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
Console trace:
Error
    at StandardRenderer.error (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:115:13)
    at Logger.emit (events.js:210:7)
    at Logger.emit (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/travis/.nvm/versions/node/v8.6.0/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
```
because `http://yui.zenfs.com/releases/yui3/yui_3.18.1.zip` is dead.

### CODE REVIEW

**Comment by sunpietro** [comment]
@adamwojs why do you want to install YUI3 from PlatformUIBundle?

**Comment by andrerom** [comment]
> why do you want to install YUI3 from PlatformUIBundle?

@sunpietro I think this is to be able to continue to run unit tests.

**Comment by sunpietro** [comment]
@andrerom right. Maybe we should find another way as bower is a deprecated depenendency management tool and at some point we might not be able to download dependencies from it anymore.

**Comment by adamwojs** [comment]
@sunpietro @andrerom Yes, this is needed for running unit tests. Example failed build: https://travis-ci.org/ezsystems/PlatformUIBundle/jobs/353246004 Sorry for non-precise PR description 😉

**Comment by sunpietro** [comment]
I'm thinking about using `composer` to install all required dependencies, like `ezsystems/platform-ui-assets-bundle`. Using `compoer` instead of `bower` will also mean updating all the paths to YUI3 in JS tests.
We'll have a single source of truth for YUI3. If YUI3 breaks in the assets bundle then we'll fix it only there. Not in 2 places.

**Comment by andrerom** [comment]
> You have to load YUI3 with composer instead. Please, drop bower usage in this repo.

@sunpietro This is for stable branch, and the repo is on the way to become obsolete by admin-ui. Switching that sounds like a unneeded change here, or?

**Comment by sunpietro** [comment]
@andrerom I have no knowledge about it.

**Pull request merged**
