### PR TITLE
EZP-23700: As an editor, I want to see an accurate url and title when I submit a form in the admin part of the PlatformUI

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: [EZP-24781](https://jira.ez.no/browse/EZP-24781) (sub-task of [EZP-23700](https://jira.ez.no/browse/EZP-23700))

# Description

Currently, most sever side form processing do an HTTP redirection to make the application display the result after the form submission. (for instance [redirecting to the section list after deleting a section](https://github.com/ezsystems/PlatformUIBundle/blob/master/Controller/SectionController.php#L137)). This kind of works except that the PlatformUI Application has no way detect such redirection (it's done transparently by the browser/XmlHTTPRequest object), as a result the application gets in an inconsistent state, the URI does not match what is actually displayed and this breaks some buttons/links.

To avoid that, the server side processing of the forms should not generate a 30X response but a 205 (*Reset Content*) response with a custom `PJAX-Location` header so that the redirection is done by the application. This patch adds this behaviour to the PlatformUI application, the server side change is to be done in [EZP-24780](https://jira.ez.no/browse/EZP-24780).

# Tests

manual test + unit

### CODE REVIEW

**Comment by dpobel** [comment]
ready for review @mhyndle @yannickroger @andrerom @StephaneDiot 
@lolautruche you can start on https://jira.ez.no/browse/EZP-24780

**Comment by lolautruche** [comment]
+1

**Comment by lolautruche** [comment]
Forget @ezrobot, I messed up CS again...

**Comment by mhyndle** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by lolautruche** [comment]
What about regular links? e.g. when clicking from admin panel sub-menu, or from admin dashboard.
We might also have redirects here, and it currently doesn't work with this change;

**Pull request merged**
