### PR TITLE
EZP-25055: Improving description text styling

### PR DESCRIPTION
**Pull request by StephaneDiot**
jira: https://jira.ez.no/browse/EZP-25055

## Description

Improving descriptiion text styling for descriptions that are in the edit field infos (image/media/relations...)

## Screenshot

image

## Tests

- Manually tested

### CODE REVIEW

**Comment by dpobel** [comment]
seems ok to me +1
ping @jince is this correct for you?

**Comment by StephaneDiot** [comment]
ping @jince, I spaced 'description' and 'help' with "1em". Check if it's as you expected.

**Comment by jince** [comment]
@StephaneDiot Perfect. 

It looks like there's no padding between the help text and the bottom of the container. Could you add a "1em" padding between the bottom of the help text and the bottom of the container?

**Comment by StephaneDiot** [comment]
@dpobel @jince  Can this one be merged?

**Pull request merged**
